# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

services:
  - xvfb
  
addons:
  apt:
    packages:
      - libftgl2 
      - libcgal-dev 
      - libglu1-mesa-dev  
      - libx11-dev 
      - libfreetype6-dev
  
env_vars:
  global:
    - RGL_USE_NULL: true
    - warnings_are_errors: false

services:
  - xvfb
  
r_binary_packages:
  - rgl
  
r_packages:
  - covr
  
after_success:
  - Rscript -e 'library(covr); codecov()'